[package]
name = "fdk-dataset-event-publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
lapin = "2.1.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
tokio = { version = "1.19.2", features = ["full"] }
tokio-executor-trait = "2.1.0"
tokio-reactor-trait = "1.1.0"
tracing = "0.1"
tracing-subscriber = "0.2"
